/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'
import { Route as AuthenticatedServicosRouteImport } from './routes/_authenticated/servicos'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedProfissionaisRouteImport } from './routes/_authenticated/profissionais'
import { Route as AuthenticatedPecasRouteImport } from './routes/_authenticated/pecas'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedInventarioRouteImport } from './routes/_authenticated/inventario'
import { Route as AuthenticatedFornecedoresRouteImport } from './routes/_authenticated/fornecedores'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedEquipamentosRouteImport } from './routes/_authenticated/equipamentos'
import { Route as AuthenticatedConciliacaoRouteImport } from './routes/_authenticated/conciliacao'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedConfigUsuariosRouteImport } from './routes/_authenticated/config.usuarios'
import { Route as AuthenticatedConfigPermissoesRouteImport } from './routes/_authenticated/config.permissoes'
import { Route as AuthenticatedConfigMeiosPagamentoRouteImport } from './routes/_authenticated/config.meios-pagamento'
import { Route as AuthenticatedConfigCategoriasRouteImport } from './routes/_authenticated/config.categorias'
import { Route as AuthenticatedConfigBancosRouteImport } from './routes/_authenticated/config.bancos'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicosRoute = AuthenticatedServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfissionaisRoute =
  AuthenticatedProfissionaisRouteImport.update({
    id: '/profissionais',
    path: '/profissionais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPecasRoute = AuthenticatedPecasRouteImport.update({
  id: '/pecas',
  path: '/pecas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventarioRoute = AuthenticatedInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFornecedoresRoute =
  AuthenticatedFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipamentosRoute =
  AuthenticatedEquipamentosRouteImport.update({
    id: '/equipamentos',
    path: '/equipamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConciliacaoRoute =
  AuthenticatedConciliacaoRouteImport.update({
    id: '/conciliacao',
    path: '/conciliacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfigUsuariosRoute =
  AuthenticatedConfigUsuariosRouteImport.update({
    id: '/config/usuarios',
    path: '/config/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfigPermissoesRoute =
  AuthenticatedConfigPermissoesRouteImport.update({
    id: '/config/permissoes',
    path: '/config/permissoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfigMeiosPagamentoRoute =
  AuthenticatedConfigMeiosPagamentoRouteImport.update({
    id: '/config/meios-pagamento',
    path: '/config/meios-pagamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfigCategoriasRoute =
  AuthenticatedConfigCategoriasRouteImport.update({
    id: '/config/categorias',
    path: '/config/categorias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfigBancosRoute =
  AuthenticatedConfigBancosRouteImport.update({
    id: '/config/bancos',
    path: '/config/bancos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/equipamentos': typeof AuthenticatedEquipamentosRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pecas': typeof AuthenticatedPecasRoute
  '/profissionais': typeof AuthenticatedProfissionaisRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/config/bancos': typeof AuthenticatedConfigBancosRoute
  '/config/categorias': typeof AuthenticatedConfigCategoriasRoute
  '/config/meios-pagamento': typeof AuthenticatedConfigMeiosPagamentoRoute
  '/config/permissoes': typeof AuthenticatedConfigPermissoesRoute
  '/config/usuarios': typeof AuthenticatedConfigUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/equipamentos': typeof AuthenticatedEquipamentosRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pecas': typeof AuthenticatedPecasRoute
  '/profissionais': typeof AuthenticatedProfissionaisRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/config/bancos': typeof AuthenticatedConfigBancosRoute
  '/config/categorias': typeof AuthenticatedConfigCategoriasRoute
  '/config/meios-pagamento': typeof AuthenticatedConfigMeiosPagamentoRoute
  '/config/permissoes': typeof AuthenticatedConfigPermissoesRoute
  '/config/usuarios': typeof AuthenticatedConfigUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/_authenticated/equipamentos': typeof AuthenticatedEquipamentosRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/_authenticated/inventario': typeof AuthenticatedInventarioRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/pecas': typeof AuthenticatedPecasRoute
  '/_authenticated/profissionais': typeof AuthenticatedProfissionaisRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/servicos': typeof AuthenticatedServicosRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/_authenticated/config/bancos': typeof AuthenticatedConfigBancosRoute
  '/_authenticated/config/categorias': typeof AuthenticatedConfigCategoriasRoute
  '/_authenticated/config/meios-pagamento': typeof AuthenticatedConfigMeiosPagamentoRoute
  '/_authenticated/config/permissoes': typeof AuthenticatedConfigPermissoesRoute
  '/_authenticated/config/usuarios': typeof AuthenticatedConfigUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clientes'
    | '/conciliacao'
    | '/equipamentos'
    | '/estoque'
    | '/financeiro'
    | '/fornecedores'
    | '/inventario'
    | '/painel'
    | '/pecas'
    | '/profissionais'
    | '/relatorios'
    | '/servicos'
    | '/vendas'
    | '/config/bancos'
    | '/config/categorias'
    | '/config/meios-pagamento'
    | '/config/permissoes'
    | '/config/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clientes'
    | '/conciliacao'
    | '/equipamentos'
    | '/estoque'
    | '/financeiro'
    | '/fornecedores'
    | '/inventario'
    | '/painel'
    | '/pecas'
    | '/profissionais'
    | '/relatorios'
    | '/servicos'
    | '/vendas'
    | '/config/bancos'
    | '/config/categorias'
    | '/config/meios-pagamento'
    | '/config/permissoes'
    | '/config/usuarios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/clientes'
    | '/_authenticated/conciliacao'
    | '/_authenticated/equipamentos'
    | '/_authenticated/estoque'
    | '/_authenticated/financeiro'
    | '/_authenticated/fornecedores'
    | '/_authenticated/inventario'
    | '/_authenticated/painel'
    | '/_authenticated/pecas'
    | '/_authenticated/profissionais'
    | '/_authenticated/relatorios'
    | '/_authenticated/servicos'
    | '/_authenticated/vendas'
    | '/_authenticated/config/bancos'
    | '/_authenticated/config/categorias'
    | '/_authenticated/config/meios-pagamento'
    | '/_authenticated/config/permissoes'
    | '/_authenticated/config/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servicos': {
      id: '/_authenticated/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AuthenticatedServicosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profissionais': {
      id: '/_authenticated/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof AuthenticatedProfissionaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pecas': {
      id: '/_authenticated/pecas'
      path: '/pecas'
      fullPath: '/pecas'
      preLoaderRoute: typeof AuthenticatedPecasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventario': {
      id: '/_authenticated/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AuthenticatedInventarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fornecedores': {
      id: '/_authenticated/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AuthenticatedFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipamentos': {
      id: '/_authenticated/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof AuthenticatedEquipamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conciliacao': {
      id: '/_authenticated/conciliacao'
      path: '/conciliacao'
      fullPath: '/conciliacao'
      preLoaderRoute: typeof AuthenticatedConciliacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config/usuarios': {
      id: '/_authenticated/config/usuarios'
      path: '/config/usuarios'
      fullPath: '/config/usuarios'
      preLoaderRoute: typeof AuthenticatedConfigUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config/permissoes': {
      id: '/_authenticated/config/permissoes'
      path: '/config/permissoes'
      fullPath: '/config/permissoes'
      preLoaderRoute: typeof AuthenticatedConfigPermissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config/meios-pagamento': {
      id: '/_authenticated/config/meios-pagamento'
      path: '/config/meios-pagamento'
      fullPath: '/config/meios-pagamento'
      preLoaderRoute: typeof AuthenticatedConfigMeiosPagamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config/categorias': {
      id: '/_authenticated/config/categorias'
      path: '/config/categorias'
      fullPath: '/config/categorias'
      preLoaderRoute: typeof AuthenticatedConfigCategoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config/bancos': {
      id: '/_authenticated/config/bancos'
      path: '/config/bancos'
      fullPath: '/config/bancos'
      preLoaderRoute: typeof AuthenticatedConfigBancosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConciliacaoRoute: typeof AuthenticatedConciliacaoRoute
  AuthenticatedEquipamentosRoute: typeof AuthenticatedEquipamentosRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedFornecedoresRoute: typeof AuthenticatedFornecedoresRoute
  AuthenticatedInventarioRoute: typeof AuthenticatedInventarioRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPecasRoute: typeof AuthenticatedPecasRoute
  AuthenticatedProfissionaisRoute: typeof AuthenticatedProfissionaisRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedServicosRoute: typeof AuthenticatedServicosRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
  AuthenticatedConfigBancosRoute: typeof AuthenticatedConfigBancosRoute
  AuthenticatedConfigCategoriasRoute: typeof AuthenticatedConfigCategoriasRoute
  AuthenticatedConfigMeiosPagamentoRoute: typeof AuthenticatedConfigMeiosPagamentoRoute
  AuthenticatedConfigPermissoesRoute: typeof AuthenticatedConfigPermissoesRoute
  AuthenticatedConfigUsuariosRoute: typeof AuthenticatedConfigUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConciliacaoRoute: AuthenticatedConciliacaoRoute,
  AuthenticatedEquipamentosRoute: AuthenticatedEquipamentosRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedFornecedoresRoute: AuthenticatedFornecedoresRoute,
  AuthenticatedInventarioRoute: AuthenticatedInventarioRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPecasRoute: AuthenticatedPecasRoute,
  AuthenticatedProfissionaisRoute: AuthenticatedProfissionaisRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedServicosRoute: AuthenticatedServicosRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
  AuthenticatedConfigBancosRoute: AuthenticatedConfigBancosRoute,
  AuthenticatedConfigCategoriasRoute: AuthenticatedConfigCategoriasRoute,
  AuthenticatedConfigMeiosPagamentoRoute:
    AuthenticatedConfigMeiosPagamentoRoute,
  AuthenticatedConfigPermissoesRoute: AuthenticatedConfigPermissoesRoute,
  AuthenticatedConfigUsuariosRoute: AuthenticatedConfigUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
